spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///temp?serverTimezone=UTC
      username: root
      password: 1234
  thymeleaf:
    cache: false
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8